### ISSUE TITLE
Logo for nsu-ed maybe?

### ISSUE THREAD

**Issue by auishik** [auishik/nsu-ed#2]
@asimuzzaman @d34thgod  Do we need a logo. _By logo I mean some illustration or shape_. Or would a simple textual logo suffice? _Having a logo does not increase any workload_ :smile:

**Comment by d34thgod** [comment]
we should keep it simple...looks better...in my opinion

**Comment by asimuzzaman** [comment]
If having a logo doesn't increase any workload then it will be great to have a logo. :smiley: I will make some textual logo tonight and post them here. Will think about illustration or shape later.

@auishik is _PNG_ OK?

**Comment by auishik** [comment]
@asimuzzaman depends on the logo :+1: . Try to keep it short and simple :cool:

**Comment by auishik** [comment]
@d34thgod :+1:

**Comment by auishik** [comment]
@d34thgod @asimuzzaman So are we having a simple textual logo? Thumbs up if you agree :smile: .

@d34thgod take a look - [emoji cheat sheet](http://www.emoji-cheat-sheet.com/) and also [markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by asimuzzaman** [comment]
@auishik :+1: I agree. :smile: 
![logo_3](https://cloud.githubusercontent.com/assets/13153797/8729447/20e501ce-2c0d-11e5-8702-728a1b4dce07.png)

**As we are going to have a black background, I made it black. Start giving suggestion :smile:**

**Comment by d34thgod** [comment]
:+1:
