### ISSUE TITLE
Finalize logo!

### ISSUE THREAD

**Issue by auishik** [auishik/nsu-ed#3]
Let us finalize our logo :smile:. @d34thgod  @asimuzzaman

**Comment by auishik** [comment]
@asimuzzaman post earlier

> @auishik :+1: I agree. :smile: 
> ![mansib-logo](https://cloud.githubusercontent.com/assets/13344621/8731671/c92c2ac6-2c1a-11e5-9a73-de4acd8f6e9f.png)
> **As we are going to have a black background, I made it black. Start giving suggestion :smile:**

**Comment by auishik** [comment]
@d34thgod  @asimuzzaman  mistakenly closed this :laughing: having fun with GitHub - so :cool:

**Comment by auishik** [comment]
Font may not go well with that of body :+1: but it was nice :clap:. Check stackoverflow or any other site - logo is simple font and goes with the site. What font and type is this? :pray: do not mind. My thoughts.

**Comment by auishik** [comment]
I will post something tomorrow! Feeling :mask: sick so no more for today!

**Comment by asimuzzaman** [comment]
Other sites tend to follow small letter with an initial capital letter, but in our case NSU is an acronym. So, we have to keep it capital all the way. According to your suggestion we can choose the font keeping match with site font. :smiley: Both of you, suggest font of your choice if you have any.

@auishik **Closed issue** can be re-opened.

**Comment by asimuzzaman** [comment]
@auishik , can you use _Trebeuchet MS_ as our site font? Then I can think about some logo with _Trebeuchet MS_.

**Comment by auishik** [comment]
@asimuzzaman  the idea is to use common or no-script fonts! You can use any basic font in that case. But don't waste too much time on this. I will look into it a little later though.

**Comment by auishik** [comment]
@asimuzzaman I am working on something :smile: . Read this [post](http://code.stephenmorley.org/html-and-css/the-myth-of-web-safe-fonts/) on web safe fonts categories. If you are free take a look at them. no :worried: worries :laughing: .

**Comment by asimuzzaman** [comment]
This time it was _Trebeuchet MS_.
![logo_v1](https://cloud.githubusercontent.com/assets/13153797/8746143/451c43fe-2ca8-11e5-9c6a-2c8cdff328e9.png)

**Comment by asimuzzaman** [comment]
And _Verdana_.
![logo_v2](https://cloud.githubusercontent.com/assets/13153797/8746230/03bd62e8-2ca9-11e5-8288-2b00da2f815b.png)

**Comment by d34thgod** [comment]
Trebeuchet MS looks better :+1:

**Comment by auishik** [comment]
Trebeuchet MS :+1:

**Comment by auishik** [comment]
Feedback please! I do not want to waste time anymore on this, @asimuzzaman logo looks great, we will implement that one :clap: :+1: 

![nsu-ed](https://cloud.githubusercontent.com/assets/13344621/8747021/d68d029e-2cb0-11e5-9d7e-75d78dead78f.png)

**Comment by asimuzzaman** [comment]
This will have conflict with our background color ( **Black** ), I think.

Please, @auishik , @d34thgod give me final feedback on _Trebeuchet_. We have lots of technical tasks left. :cry:

**Comment by auishik** [comment]
Will background be black because blue and black does not go well!

**Comment by auishik** [comment]
@asimuzzaman I know! The amount of pages is too dam high plus the amount of modules too! :sob: . Keep this issue as our lowest priority. Technical issues are coming soon.

**Comment by asimuzzaman** [comment]
@auishik , for example _StackExchange_ has blue and black or you can see [this](https://www.google.com/search?q=logos+with+blue+and+black&tbm=isch&tbo=u&source=univ&sa=X&ved=0CB0QsARqFQoTCP-h0PS-4sYCFYyRjgodFPUCkQ&biw=1134&bih=581) obviously in your free time :smile:

**Comment by auishik** [comment]
:+1:  like the blue black of the "finetubes" logo, we can do something like the **_stackexchange**_. Like we could do -
1. thinner top-bar - so more space for the user to view content on widescreen displays.
2. so logo textual and blue and black
3. user panel in top bar can be given as drop-down with links to user profile and setting

**Comment by asimuzzaman** [comment]
Yeah, I agree with that. Moreover, those were my plan too. :smile: But, as it is more your ( @auishik ) task than ours so final decision about the top bar size or drop-downs will better be taken by you.

**Comment by auishik** [comment]
ok! I will then close this issue :smile: first successful feature addition. :smile:
1. thinner top-bar - so more space for the user to view content on widescreen displays.
2. so logo textual and blue and black
3. user panel in top bar can be given as drop-down with links to user profile and settings
