### ISSUE TITLE
Configured your text editor according to the ".editorconfig" file?

### ISSUE THREAD

**Issue by auishik** [auishik/nsu-ed#5]
Just a heads up! so that we all are in the same page! :smile: Thumbs up if you did already! Help required? - @asimuzzaman will help :smiley: !

**Comment by asimuzzaman** [comment]
We should follow same .editorconfig file for our coding purpose. Soon, I will upload one here. Let's have some discussion-

Indentation size= 4, how is it?

**Comment by auishik** [comment]
:unamused: It is already given in the repo! long before. [here](https://github.com/auishik/nsu-ed/blob/master/.editorconfig)

**Comment by auishik** [comment]
Indentation size is 4 but type is space. Please have a look. :smile:

**Comment by asimuzzaman** [comment]
Yeah, this **.editorconfig** is ideal for coding. :+1: 

@d34thgod , please report that you have configured that editor configuration with your _text editor_ then we will close this issue.

**Comment by auishik** [comment]
I think we should use indentation-size: 2 type:space

**Comment by asimuzzaman** [comment]
4 is OK. Most of the people use it as it makes others' code easily understandable for better space.

**Comment by auishik** [comment]
ok!

**Comment by asimuzzaman** [comment]
No problem, if you find it more comfortable you can change it. :smiley:

**Comment by auishik** [comment]
We have to change it because the html code has a lot of depth! I am changing the **.editorconfig**.

**Comment by d34thgod** [comment]
so  4 naki 2....

**Comment by auishik** [comment]
Changed **.editorconfig**.

**Comment by d34thgod** [comment]
ok done :dancer:

**Comment by auishik** [comment]
@d34thgod  Which text editor?

**Comment by d34thgod** [comment]
atom

**Comment by auishik** [comment]
indentation type should be space
