### ISSUE TITLE
Topbar UI - narrow, name badge on drop down, logo

### ISSUE THREAD

**Issue by auishik** [auishik/nsu-ed#6]
@d34thgod @asimuzzaman just created this to keep note of any feature that needs to be implemented! Issue would be closed when it is implemented. Any thoughts during implementation would be posted here :smile: .

**Comment by asimuzzaman** [comment]
@auishik , how complicated is the designing of **drop down** menu feature?

**Comment by auishik** [comment]
Not so :smile: . I guess it is built right into bootstrap. I will look into it. If not built in, it is easy enough for me :smile:

**Comment by auishik** [comment]
Ok! This feature has been implemented :+1:  I will upload all the html tomorrow. Close this issue if satisfied after viewing the top-bar feature.

**Comment by asimuzzaman** [comment]
Ok we will. :+1:

**Comment by asimuzzaman** [comment]
Closing this issue, I am satisfied with the top bar feature. :smile:
