### ISSUE TITLE
Making reusable PHP functions

### ISSUE THREAD

**Issue by asimuzzaman** [auishik/nsu-ed#7]
Hello coders,

Instead of writing same functions again and again we can write **global functions** to make it once and use it any time. For example, we need a function **add($val1, $val2)** in our several **PHP** codes which will add two numbers and return the sum. Instead of writing the function again again we can do this:

We can put the function in our **functions.php** like this-

``` php
<?php
 function add($val1, $val2)
{
  return $val1 + $val2;
}
?>
```

and let's say in another file **code.php** we use them by calling **include()** or **require()** or **require_once()** functions -

``` php
<?php
  require_once(functions.php); //including all functions from functions.php file
  $val1= 3;
  $val2= 4;
  $result= add(3,4);
?>
```

Please keep this practice to make our functions reusable. :smile:

**Comment by auishik** [comment]
@asimuzzaman yes we would also start a UML diagram if possible and print it out. Just a rough one would do - so that everyone knows what does what.

**Comment by asimuzzaman** [comment]
@auishik let me study on UML a bit more. :stuck_out_tongue: I want to add **includes** folder in our directory.

**Comment by auishik** [comment]
Think about the contents of the include! We will discuss this soon!

**Comment by asimuzzaman** [comment]
Yes, I have just added raw function, soon the whole function will be committed. Before that I am going to post a issue on **MySQL**.
