### ISSUE TITLE
Changing MySQL user password

### ISSUE THREAD

**Issue by asimuzzaman** [auishik/nsu-ed#9]
To make our **PHP** code run in our local machine and **koding.io** we need to have same _username_ and _password_ for our MySQL server. At first I thought about creating new user for our project, but keeping **root** as our project username will make things easier for us. So, please change your MySQL **root** password to **1234**.  The procedure for changing password is given below-

From **cmd** or **terminal** start MySQL console

``` shell
$ mysql -u root -p
```

Then enter the current password. In the MySQL console write following commands

``` shell
mysql> UPDATE user SET Password=PASSWORD('1234') WHERE User='root';
mysql> FLUSH PRIVILEGES;
mysql> exit;
```

When all of you are done then close this issue :smile:

**Comment by auishik** [comment]
OK I will configure it as given

**Comment by d34thgod** [comment]
ho ho man amr ta already kore felse
